name: Fake Duration Video

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Generate Fake Duration Video
        run: |
          mkdir -p output
          # 用 lavfi 生成一个 5 秒白色视频作为 input.mp4
          ffmpeg -y -f lavfi -i color=c=white:s=640x480:d=5 -an input.mp4
          # 按图片里的命令伪装时长
          ffmpeg -i input.mp4 -filter_complex \
          "[0]trim=end=5,setpts=PTS-STARTPTS[v1]; \
           [0]trim=start=5,setpts=PTS-PTS[v2]; \
           [v1][v2]concat=n=2:v=1:a=0" \
          output/fake_duration.mp4

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fake-duration-video
          path: output/fake_duration.mp4