name: Generate Fake 11min Video

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Generate 11 min black video
        run: |
          ffmpeg -f lavfi -i color=c=black:s=160x90:d=660 -pix_fmt yuv420p input.mp4
          echo "生成 11 分钟黑色视频完成"

      - name: Process the video (split and concat, if needed)
        run: |
          # 如果需要拼接或者分割，执行以下命令
          ffmpeg -i input.mp4 -filter_complex "[0]trim=end=5,setpts=PTS-STARTPTS[v1];[0]trim=start=5,setpts=PTS-STARTPTS[v2];[v1][v2]concat=n=2:v=1:a=0 -t 10 fake.mp4"
          echo "视频处理完成"

      - name: Upload fake video
        uses: actions/upload-artifact@v4
        with:
          name: fake_11min_video
          path: input.mp4