name: Generate Fake Eternal Video

on:
  workflow_dispatch:   # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Generate Fake Eternal Video
        run: |
          mkdir -p output
          ffmpeg -y -f lavfi -i color=c=white:s=640x480:d=5 \
          -vf "setpts=PTS*1000000000" -an output/fake_eternal.mp4

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fake-eternal-video
          path: output/fake_eternal.mp4