name: Generate Fake Long Video

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Generate long black video
        run: |
          ffmpeg -f lavfi -i color=c=black:s=160x90:d="14400000" -r 0.0000000694444444444 -pix_fmt yuv420p input.mp4
          echo "生成超长黑色视频完成"

      - name: Process video (split and concat)
        run: |
          ffmpeg -i input.mp4 -filter_complex "[0]trim=end=5,setpts=PTS-STARTPTS[v1];[0]trim=start=5,setpts=PTS-PTS[v2];[v1][v2]concat=n=2:v=1:a=0" -t 10 "你这视频不对啊.mp4"
          echo "视频处理完成"

      - name: Upload processed video
        uses: actions/upload-artifact@v4
        with:
          name: fake_long_video
          path: "你这视频不对啊.mp4"