name: Generate Fake Long Video

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Get audio duration
        id: get_dur
        run: |
          dur=$(ffprobe -i audio.mp3 -show_entries format=duration -v quiet -of csv="p=0")
          echo "duration=$dur" >> $GITHUB_ENV
          echo "音频时长: $dur 秒"

      - name: Generate black video with same length as audio
        run: |
          ffmpeg -f lavfi -i color=c=black:s=160x90:r=1 -t ${{ env.duration }} -pix_fmt yuv420p silent_black.mp4
          echo "生成与音频等长的黑色视频完成"

      - name: Combine with audio
        run: |
          ffmpeg -i silent_black.mp4 -i audio.mp3 -c:v copy -c:a aac -shortest input.mp4
          echo "黑色视频与音频合并完成"

      - name: Process video (split and concat)
        run: |
          ffmpeg -i input.mp4 -filter_complex "[0:v]trim=end=5,setpts=PTS-STARTPTS[v1];[0:v]trim=start=5,setpts=PTS-PTS[v2];[v1][v2]concat=n=2:v=1:a=0" \
          -map 1:a -c:a copy -t 10 "创意文画1629.mp4"
          echo "视频处理完成"

      - name: Upload processed video
        uses: actions/upload-artifact@v4
        with:
          name: fake_long_video
          path: "创意文画1629.mp4"