name: Generate Fake Long Video

on:
  workflow_dispatch:
    inputs:
      duration_seconds:
        description: '伪造的时长（秒）。默认 2147483647，大约 68 年）'
        required: false
        default: '2147483647'
      output_name:
        description: '输出文件名'
        required: false
        default: 'fake_long.mp4'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Generate short sample (black video + silent audio)
        run: |
          ffmpeg -f lavfi -i color=c=black:s=160x90:d=0.1 \
                 -f lavfi -i anullsrc=channel_layout=stereo:sample_rate=44100 \
                 -shortest -c:v libx264 -preset veryfast -crf 28 -pix_fmt yuv420p \
                 -c:a aac -b:a 32k -movflags +faststart -y short.mp4
          ls -lh short.mp4

      - name: Patch MP4 header to fake duration (base64-safe)
        env:
          DURATION: ${{ github.event.inputs.duration_seconds }}
          OUTPUT: ${{ github.event.inputs.output_name }}
        run: |
          echo 'IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMwppbXBvcnQgc3lzLCBzdHJ1Y3QKCmRlZiByZWFkX3VpbnQzMihiKQ==' | base64 -d > patch_duration.py
          chmod +x patch_duration.py
          python3 patch_duration.py short.mp4 "$OUTPUT" "$DURATION"
          ls -lh "$OUTPUT" || true
          ffprobe -v quiet -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$OUTPUT" || true

      - name: Upload processed video (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: fake_long_video
          path: ${{ github.event.inputs.output_name }}